language: java
cache:
  directories:
    - "$HOME/.cache"
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch --yes
deploy:
  provider: script
  script: "cd onfido-java &&
           echo \"no-tty\" >> ~/.gnupg/gpg.conf &&
           mvn clean deploy --settings ../.maven.xml -DskipTests=true -B -U -Prelease -Dgpg.passphrase=$GPG_PASSPHRASE"
  skip_cleanup: true
  on:
    branch: test-release
