language: java
cache:
  directories:
    - "$HOME/.cache"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml &&
           cd onfido-java &&
           mvn deploy -P release"
  skip_cleanup: true
  on:
    branch: master
    tags: true
